"""init_fix_endereco

Revision ID: 0522072d08b5
Revises: 5f0b82d658a6
Create Date: 2024-08-29 15:59:16.439572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0522072d08b5'
down_revision: Union[str, None] = '5f0b82d658a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('endereco', sa.String(length=60), nullable=False))
    op.drop_column('centros_treinamento', 'endereço')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('endereço', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('centros_treinamento', 'endereco')
    # ### end Alembic commands ###
